# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QuZ1ciYhmvV41ZESgAg7/m/T8ZyDVDSJNlu9fVbWdUeww+Az1zc0kQnENMwZTHCfRRAHyGZYP0EibkOqfhF6VPzB7izbSYVMVtm/O29H+W8HkuIKDjwOBWmMfviIMVwOwIQUWfYrafXtPR1Ebuj+h5pp0bTvkwKYDp5IJBmHWjJ+IqNXCVuHSr28nt/WfwjvTfCX74Ce6qhDvx/NzdAqMgw5smngNDtGmq1I2livwKGdt22w+knZrTYRNdaEni1+Lxoqz2idV6NF9+SKQxClSNgzxIdpWNflQPSVBduk9BqzoWb51mtdV02ol0UghN8B3VDERdu3P3wIlCa+zu4ltKVGVcM35PgdpfsIx8N0H/lDYzB9C8EItyW8xmr3PuEAMQleHQaO+egnq20LyBWx4Xr/d5RzMpyfhIkgiIOYsLwo8IZxzgG2VqrPgPSQ3yOG8ZcN3MEX9r8tEGJ97vz/uFOrUdMB6ySxYGhCxQpOGhsf32etoUl5Y9uWK5Mq5mhtHuOTGpdhYWUd+iaJWWgWL0yMdqgfBICXRHMZBSahC1JtLsz6MQbEE8NgwFnjyK9HsQf7/5y6jEZ+VEz7Gnn9NiYIizadDrn3GRiJE9ZV9KQAu8l05/I2TeKkLpST9kt4/nEdcJMKLyvN33eOV8rbw1Cd5oc+QmwVtDUGlxvnfNE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
