travis:
  secure:
    BINSTAR_TOKEN: yCzl4HpVnAUl47Khy+cpfIMl+s8d/l4O+uDlteJDQuLiPy41oYOgbWAvuGxOAn8kA6JNP0BMtbrwnUqlpdJqI1G7VPt8JalMsctR7eSHqmLmqENBHG+2h2KNUdGcrAiWuxRbkFqDQz0HWdFAuhonl3k+6lulbICL+BT5CtSenECYnoABECdnBBePhLUuPzwmRzRRiEx6QlZz1TZYkHBtxDAOJsQxMaEbz+UQj02PU3/S2cD6ATZZLIA6ou+BNicUo/Rc7fIv6uhxjrvglIeXp248knhRIK5h24SSPxp9Pcs79YmVcwVJUnaLXKCcb+vjyXZmLcJoeiFR5i44CQXrp+5ggqVa6FWizqJYEQQ9DzeJByAyHOpcNekxHjRb8GekhObOqFHP/Rd5Ulzlw5k0CK7E9ZHZfpjje6Yc471r2XY4U5t8Tqym4zsUaUwCsgGZYNO13/DEF3BDLCYYw+iuwOkG920H6FMtn+ktXJgaQ8OlrbDf5q5WqR1TkMqMXiIY5NdgUnQskx6Gq8XUqXsUjmQd8ElJsTq49TV2obBbvuaCCNCxejuMYyt1T/y7ySGOJWXHtMCk8TBD1JMZrZ83tjpbzzNtQz97GkoHVMlphPNcspCwdyrU9FEial0gInhCpOI9hrgvGH/W53aknFyhkzx/TTdvmhNCw3glaReODmY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
